### ISSUE TITLE
Restore the starter startup mode

### ISSUE THREAD

**Issue by polunzh** [ArcBlock/forge-cli#170]
Add a `mode` conception to determine whether start by `forge starter`:

1. `production` mode: start by forge starter, because more stable, can only start one chain;
1. `development` mode: start without forge starter, support multiple chain.

cc: @tyrchen @wangshijun @dingpl716 @sunboshan

**Comment by polunzh** [comment]
Default mode will be development mode.

**Comment by wangshijun** [comment]
Since we have a global configuration to switch between `multiple-chain` and `single-chain` support mode:

- Set `allowMultiChain: false` in `~/.forgerc.yml`, forge-cli will **not allow** `chain:create` command and user `forge_starter` to start chains
- Set `allowMultChain: true` or ignore this config, forge-cli will support multiple chains.
